export enum NotificationType {
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  INVOICE_CREATED = 'INVOICE_CREATED',
  INVOICE_PAID = 'INVOICE_PAID',
  PROJECT_MEMBER_ADDED = 'PROJECT_MEMBER_ADDED',
  SYSTEM_ALERT = 'SYSTEM_ALERT',
}

export enum ResourceType {
  TASK = 'TASK',
  INVOICE = 'INVOICE',
  PROJECT = 'PROJECT',
  USER = 'USER',
}
